routes:

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: 'tag:gallery'
  /posts/:
    permalink: /{slug}/
    template: posts
    data: page.posts

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/